# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\modularisationQTui\sqlinputdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SQLInputDialog(object):
    def setupUi(self, SQLInputDialog):
        SQLInputDialog.setObjectName("SQLInputDialog")
        SQLInputDialog.resize(451, 254)
        self.verticalLayout = QtWidgets.QVBoxLayout(SQLInputDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.partSQLinputInfotable = QtWidgets.QTableWidget(SQLInputDialog)
        self.partSQLinputInfotable.setObjectName("partSQLinputInfotable")
        self.partSQLinputInfotable.setColumnCount(3)
        self.partSQLinputInfotable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.partSQLinputInfotable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.partSQLinputInfotable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.partSQLinputInfotable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.partSQLinputInfotable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.partSQLinputInfotable.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.partSQLinputInfotable)
        self.buttonBox = QtWidgets.QDialogButtonBox(SQLInputDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(SQLInputDialog)
        self.buttonBox.accepted.connect(SQLInputDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(SQLInputDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SQLInputDialog)

    def retranslateUi(self, SQLInputDialog):
        _translate = QtCore.QCoreApplication.translate
        SQLInputDialog.setWindowTitle(_translate("SQLInputDialog", "Dialog"))
        item = self.partSQLinputInfotable.verticalHeaderItem(0)
        item.setText(_translate("SQLInputDialog", "info"))
        item = self.partSQLinputInfotable.verticalHeaderItem(1)
        item.setText(_translate("SQLInputDialog", "operatiion"))
        item = self.partSQLinputInfotable.horizontalHeaderItem(0)
        item.setText(_translate("SQLInputDialog", "PartID"))
        item = self.partSQLinputInfotable.horizontalHeaderItem(1)
        item.setText(_translate("SQLInputDialog", "ConnectPartID"))
        item = self.partSQLinputInfotable.horizontalHeaderItem(2)
        item.setText(_translate("SQLInputDialog", "FunctionID"))
